package cn.duc.global.repository.model.generator;

import cn.duc.global.base.BaseClassName;
import plugin.BaseModel;

@SuppressWarnings("serial")
@BaseClassName("SzyYsj")
public class SzyYsj extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szy_ysj.duc_user_id
     *
     * @mbggenerated
     */
    private String ducUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szy_ysj.user_name1
     *
     * @mbggenerated
     */
    private String userName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szy_ysj.phone_number1
     *
     * @mbggenerated
     */
    private String phoneNumber1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szy_ysj.password1
     *
     * @mbggenerated
     */
    private String password1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szy_ysj.locked1
     *
     * @mbggenerated
     */
    private Boolean locked1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column szy_ysj.login_log_id1
     *
     * @mbggenerated
     */
    private String loginLogId1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szy_ysj.duc_user_id
     *
     * @return the value of szy_ysj.duc_user_id
     *
     * @mbggenerated
     */
    public String getDucUserId() {
        return ducUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szy_ysj.duc_user_id
     *
     * @param ducUserId the value for szy_ysj.duc_user_id
     *
     * @mbggenerated
     */
    public void setDucUserId(String ducUserId) {
        this.ducUserId = ducUserId == null ? null : ducUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szy_ysj.user_name1
     *
     * @return the value of szy_ysj.user_name1
     *
     * @mbggenerated
     */
    public String getUserName1() {
        return userName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szy_ysj.user_name1
     *
     * @param userName1 the value for szy_ysj.user_name1
     *
     * @mbggenerated
     */
    public void setUserName1(String userName1) {
        this.userName1 = userName1 == null ? null : userName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szy_ysj.phone_number1
     *
     * @return the value of szy_ysj.phone_number1
     *
     * @mbggenerated
     */
    public String getPhoneNumber1() {
        return phoneNumber1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szy_ysj.phone_number1
     *
     * @param phoneNumber1 the value for szy_ysj.phone_number1
     *
     * @mbggenerated
     */
    public void setPhoneNumber1(String phoneNumber1) {
        this.phoneNumber1 = phoneNumber1 == null ? null : phoneNumber1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szy_ysj.password1
     *
     * @return the value of szy_ysj.password1
     *
     * @mbggenerated
     */
    public String getPassword1() {
        return password1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szy_ysj.password1
     *
     * @param password1 the value for szy_ysj.password1
     *
     * @mbggenerated
     */
    public void setPassword1(String password1) {
        this.password1 = password1 == null ? null : password1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szy_ysj.locked1
     *
     * @return the value of szy_ysj.locked1
     *
     * @mbggenerated
     */
    public Boolean getLocked1() {
        return locked1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szy_ysj.locked1
     *
     * @param locked1 the value for szy_ysj.locked1
     *
     * @mbggenerated
     */
    public void setLocked1(Boolean locked1) {
        this.locked1 = locked1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column szy_ysj.login_log_id1
     *
     * @return the value of szy_ysj.login_log_id1
     *
     * @mbggenerated
     */
    public String getLoginLogId1() {
        return loginLogId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column szy_ysj.login_log_id1
     *
     * @param loginLogId1 the value for szy_ysj.login_log_id1
     *
     * @mbggenerated
     */
    public void setLoginLogId1(String loginLogId1) {
        this.loginLogId1 = loginLogId1 == null ? null : loginLogId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szy_ysj
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ducUserId=").append(ducUserId);
        sb.append(", userName1=").append(userName1);
        sb.append(", phoneNumber1=").append(phoneNumber1);
        sb.append(", password1=").append(password1);
        sb.append(", locked1=").append(locked1);
        sb.append(", loginLogId1=").append(loginLogId1);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szy_ysj
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SzyYsj other = (SzyYsj) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDucUserId() == null ? other.getDucUserId() == null : this.getDucUserId().equals(other.getDucUserId()))
            && (this.getUserName1() == null ? other.getUserName1() == null : this.getUserName1().equals(other.getUserName1()))
            && (this.getPhoneNumber1() == null ? other.getPhoneNumber1() == null : this.getPhoneNumber1().equals(other.getPhoneNumber1()))
            && (this.getPassword1() == null ? other.getPassword1() == null : this.getPassword1().equals(other.getPassword1()))
            && (this.getLocked1() == null ? other.getLocked1() == null : this.getLocked1().equals(other.getLocked1()))
            && (this.getLoginLogId1() == null ? other.getLoginLogId1() == null : this.getLoginLogId1().equals(other.getLoginLogId1()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table szy_ysj
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDucUserId() == null) ? 0 : getDucUserId().hashCode());
        result = prime * result + ((getUserName1() == null) ? 0 : getUserName1().hashCode());
        result = prime * result + ((getPhoneNumber1() == null) ? 0 : getPhoneNumber1().hashCode());
        result = prime * result + ((getPassword1() == null) ? 0 : getPassword1().hashCode());
        result = prime * result + ((getLocked1() == null) ? 0 : getLocked1().hashCode());
        result = prime * result + ((getLoginLogId1() == null) ? 0 : getLoginLogId1().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        return result;
    }
}