server:
  port: ${SERVICE_PORT:8000}
  context-path: /api

#logging:
#  level:
#    org.springframework.cloud: 'DEBUG'
#    org.hibernate.type.descriptor.sql.BasicBinder: 'TRACE'

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.duc.global.repository.model

  #mapper:
  #    mappers:
  #        - com.antsoft.database.BaseMapper
  #    not-empty: false
  #    identity: MYSQL

pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql
#security:
#  basic:
#    authorize-mode: none
