#spring:
#  devtools:
#    restart:
#      enabled: true
#  datasource:
#    url: "jdbc:mysql://172.18.11.22:3306/video_management?useUnicode=true&characterEncoding=utf-8"
#    username: "video_user"
#    password: "89345r%vVd"
